{% set name = "samsungtvws" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c2a70a2aa878c9584f239e37f030fbcb0b583bb7ae189ccbfeaaf77eb244038

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - websocket-client >=0.57.0
    - requests >=2.21.0

test:
  imports:
    - samsungtvws
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/xchwarze/samsung-tv-ws-api
  summary: Samsung Smart TV WS API wrapper
  description: |
    This project is a library for remote controlling Samsung televisions via a TCP/IP connection.
    It currently supports modern (post-2016) TVs with Ethernet or Wi-Fi connectivity. They should be all models with TizenOs.
    Based on https://github.com/marysieek/samsung-tv-api work.
  license: LGPL-3.0
  license_family: LGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mlondschien
    - xchwarze
